<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="camera_thickness" value="0.025" />
    <xacro:property name="camera_width" value="0.05" />
    <xacro:property name="camera_height" value="0.05" />

    <xacro:macro name="camera_macro" params="parent x_pos y_pos z_pos">
        <link name="camera_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${camera_thickness} ${camera_width} ${camera_height}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${camera_thickness} ${camera_width} ${camera_height}"/>
                </geometry>
            </collision>
        </link>
        <joint name="camera_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="camera_link"/>
            <origin xyz="${x_pos} ${y_pos} ${z_pos-camera_height/2-0.005}" rpy="0 0 0"/>
        </joint>

        <gazebo reference="camera_link">
            <sensor type="camera" name="camera">
                <update_rate>30.0</update_rate>
                <camera>
                    <horizontal_fov>1.3962634</horizontal_fov>
                    <image>
                        <width>640</width>
                        <height>480</height>
                        <format>R8G8B8</format>
                    </image>
                    <clip>
                        <near>0.02</near>
                        <far>300</far>
                    </clip>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.007</stddev>
                    </noise>
                </camera>
                <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                    <alwaysOn>true</alwaysOn>
                    <updateRate>0.0</updateRate>
                    <cameraName>camera</cameraName>
                    <imageTopicName>image_raw</imageTopicName>
                    <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                    <frameName>camera_link</frameName>
                    <hackBaseline>0.07</hackBaseline>
                    <distortionK1>0.0</distortionK1>
                    <distortionK2>0.0</distortionK2>
                    <distortionK3>0.0</distortionK3>
                    <distortionT1>0.0</distortionT1>
                    <distortionT2>0.0</distortionT2>
                </plugin>
            </sensor>
            <material>Gazebo/Red</material>
        </gazebo>

    </xacro:macro>
</robot>
