<?xml version="1.0"?>
<robot name="dribot"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="materials.xacro" />
    <xacro:include filename="macros.xacro" />
    <xacro:include filename="wheel.xacro" />
    <xacro:include filename="camera.xacro" />
    <xacro:include filename="lidar.xacro" />
    <xacro:include filename="imu.xacro" />

    <xacro:property name="base_diameter" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="base_weight" value="18.0" />

    <xacro:property name="driving_wheel_diameter" value="0.15" />
    <xacro:property name="driving_wheel_thickness" value="0.03" />
    <xacro:property name="driving_wheel_weight" value="0.5" />
    <xacro:property name="driving_wheel_base_gap" value="0.01" />

    <xacro:property name="caster_wheel_weight" value="0.1" />

    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${base_diameter/2}" length="${base_height}"/>
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${base_diameter/2}" length="${base_height}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="${base_weight}" r="${base_diameter/2}" h="${base_height}" roll="0"/>
    </link>

    <link name="base_footprint">
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0.0 0.0 ${-(base_height/2+driving_wheel_diameter/4)}" rpy="0 0 0"/>
    </joint>

    <xacro:driving_wheel suffix="left" reflect="1"/>
    <xacro:driving_wheel suffix="right" reflect="-1"/>

    <xacro:caster_wheel suffix="front" reflect="1"/>
    <xacro:caster_wheel suffix="back" reflect="-1"/>

    <xacro:camera_macro parent="base_link" x_pos="${base_diameter/2}" y_pos="0" z_pos="${base_height/2}" />

    <xacro:lidar parent="base_link" x_pos="0" y_pos="0" z_pos="${base_height/2}" />

    <xacro:imu_macro parent="base_link" x_pos="0.1" y_pos="0" z_pos="${base_height/2}" />

    <xacro:include filename="plugins.xacro" />

</robot>
