<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="lidar_radius" value="0.04" />
    <xacro:property name="lidar_height" value="0.04" />

    <xacro:macro name="lidar" params="parent x_pos y_pos z_pos">
        <link name="lidar_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
                </geometry>
            </collision>
        </link>
        <joint name="lidar_joint" type="fixed">
            <parent link="${parent}"/>
            <child link="lidar_link"/>
            <origin xyz="${x_pos} ${y_pos} ${z_pos+lidar_height/2}" rpy="0 0 0"/>
        </joint>

        <gazebo reference="lidar_link">
            <sensor name="lidar" type="ray">
                <always_on>true</always_on>
                <visualize>false</visualize>
                <pose>0.0 0 0.0 0 0 0</pose>
                <update_rate>10</update_rate>
                <ray>
                    <scan>
                        <horizontal>
                            <samples>667</samples>
                            <resolution>0.9</resolution>
                            <min_angle>0.000000</min_angle>
                            <max_angle>6.280000</max_angle>
                        </horizontal>
                    </scan>
                    <range>
                        <min>0.200000</min>
                        <max>16</max>
                        <resolution>0.9</resolution>
                    </range>
                    <noise>
                        <type>gaussian</type>
                        <mean>0.0</mean>
                        <stddev>0.01</stddev>
                    </noise>
                </ray>
                <plugin name="bytes_laserscan" filename="libgazebo_ros_ray_sensor.so">
                    <ros>
                        <namespace>/</namespace>
                        <remapping>~/out:=scan</remapping>
                    </ros>
                    <output_type>sensor_msgs/LaserScan</output_type>
                </plugin>
            </sensor>
            <material>Gazebo/Purple</material>
        </gazebo>
    </xacro:macro>
</robot>
