<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <gazebo>

        <!-- Use gazebo_ros_joint_state_publisher instead of publishWheelJointState -->
        <plugin name="joint_states" filename="libgazebo_ros_joint_state_publisher.so">
            <joint_name>driving_wheel_right_joint</joint_name>
            <joint_name>driving_wheel_left_joint</joint_name>
        </plugin>

        <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>

            <update_rate>100</update_rate>
            <left_joint>driving_wheel_left_joint</left_joint>
            <right_joint>driving_wheel_right_joint</right_joint>
            <wheel_separation>${base_diameter+(driving_wheel_base_gap*2)}</wheel_separation>
            <wheel_diameter>${driving_wheel_diameter}</wheel_diameter>

            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_link</robot_base_frame>

            <max_wheel_torque>20</max_wheel_torque>
            <max_acceleration>1.0</max_acceleration>

            <publish_odom>true</publish_odom>
            <publish_odom_tf>false</publish_odom_tf>
            <publish_wheel_tf>false</publish_wheel_tf>

        </plugin>
    </gazebo>
</robot>
